// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApvEbLpY-kNCDrvJ6tLOCyKe4_-nIafzM',
    appId: '1:221348451414:web:025a487f71f27f9d3f57f7',
    messagingSenderId: '221348451414',
    projectId: 'clothesapp-7743b',
    authDomain: 'clothesapp-7743b.firebaseapp.com',
    storageBucket: 'clothesapp-7743b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZpxIJvNUJaiZ1Wxtizlnk7asHR3_cUDI',
    appId: '1:221348451414:android:f8549e2f2fddf1563f57f7',
    messagingSenderId: '221348451414',
    projectId: 'clothesapp-7743b',
    storageBucket: 'clothesapp-7743b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw-SCc3R7tgd_-f3NEqNmoOxY06Sma0Vc',
    appId: '1:221348451414:ios:f41666998f50eeb83f57f7',
    messagingSenderId: '221348451414',
    projectId: 'clothesapp-7743b',
    storageBucket: 'clothesapp-7743b.firebasestorage.app',
    iosBundleId: 'com.example.clothesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw-SCc3R7tgd_-f3NEqNmoOxY06Sma0Vc',
    appId: '1:221348451414:ios:f41666998f50eeb83f57f7',
    messagingSenderId: '221348451414',
    projectId: 'clothesapp-7743b',
    storageBucket: 'clothesapp-7743b.firebasestorage.app',
    iosBundleId: 'com.example.clothesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApvEbLpY-kNCDrvJ6tLOCyKe4_-nIafzM',
    appId: '1:221348451414:web:6476b14de170c7243f57f7',
    messagingSenderId: '221348451414',
    projectId: 'clothesapp-7743b',
    authDomain: 'clothesapp-7743b.firebaseapp.com',
    storageBucket: 'clothesapp-7743b.firebasestorage.app',
  );
}
